site_name: FoodSpec
site_url: https://chandrasekarnarayana.github.io/foodspec/
repo_url: https://github.com/chandrasekarnarayana/foodspec

theme:
  name: "material"

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api_reference.md
  - CLI Usage: cli.md
  - Libraries: libraries.md

  - Tutorials:
      - FTIR & Raman Preprocessing: ftir_raman_preprocessing.md
      - Heating Tutorial: heating_tutorial.md
      - Oil Authentication Workflow: oil_auth_tutorial.md
      - QC Workflow: qc_tutorial.md
      - Validation – Baseline Models: validation_baseline.md
      - Validation – Peak Ratios: validation_peak_ratios.md

  - Domains & Methods:
      - Spectral Domains Overview: domains_overview.md
      - Hyperspectral: hyperspectral.md
      - Chemometrics for Edible Oils: validation_chemometrics_oils.md
      - MethodsX Protocol: methodsx_protocol.md
      - Advanced Deep Learning: advanced_deep_learning.md

  - Model Registry: model_registry.md
  - Citing FoodSpec: citing.md

  - Design Documentation:
      - Overview: design/01_overview.md
